<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@3.8">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@2.90">
    <parentIds>
      <string>7</string>
    </parentIds>
    <id>8</id>
    <descriptorId>org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@2.90">
      <arguments>
        <entry>
          <string>job</string>
          <string>build_backend</string>
        </entry>
        <entry>
          <string>parameters</string>
          <list>
            <org.jenkinsci.plugins.workflow.cps.UninstantiatedDescribableWithInterpolation>
              <symbol>string</symbol>
              <arguments class="linked-hash-map">
                <entry>
                  <string>name</string>
                  <string>Version</string>
                </entry>
                <entry>
                  <string>value</string>
                  <string>$Version</string>
                </entry>
              </arguments>
              <interpolatedStrings/>
            </org.jenkinsci.plugins.workflow.cps.UninstantiatedDescribableWithInterpolation>
          </list>
        </entry>
      </arguments>
      <sensitiveVariables/>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@2.41">
      <startTime>1616144376291</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.LabelAction plugin="workflow-api@2.41">
      <displayName>Building build_backend</displayName>
    </wf.a.LabelAction>
    <wf.a.ErrorAction plugin="workflow-api@2.41">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.23">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerListener.onCompleted(BuildTriggerListener.java:53)</trace>
          <trace>hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)</trace>
          <trace>hudson.model.Run.execute(Run.java:1952)</trace>
          <trace>hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)</trace>
          <trace>hudson.model.ResourceController.execute(ResourceController.java:97)</trace>
          <trace>hudson.model.Executor.run(Executor.java:429)</trace>
        </stackTrace>
        <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
          <c class="list"/>
          <list reference="../c"/>
        </suppressedExceptions>
        <result>
          <name>FAILURE</name>
          <ordinal>2</ordinal>
          <color>RED</color>
          <completeBuild>true</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <org.jenkinsci.plugins.workflow.support.steps.build.DownstreamFailureCause plugin="pipeline-build-step@2.13">
              <id>build_backend#15</id>
            </org.jenkinsci.plugins.workflow.support.steps.build.DownstreamFailureCause>
          </a>
        </causes>
        <actualInterruption>false</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>